export const yachtData = (data) => {

    let obj = {
            // ...data.yacht,

            // user_id:1,
            // yacht:data.yacht.id,
            // min_price: String(data.yacht.min_price),
            // max_price: String(data.yacht.max_price),
            // guest: String(data.yacht.guest),
            // cancel_time_in_hour: String(data.yacht.cancel_time_in_hour),
            // duration_hour: String(data.yacht.duration_hour),
            // duration_minutes: String(data.yacht.duration_minutes),
            // number_of_cabin: String(data.yacht.number_of_cabin),
            // capacity: String(data.yacht.capacity),
            // sleep_capacity: String(data.yacht.sleep_capacity),
            // per_day_price: String(data.yacht.per_day_price),
            // per_hour_price: String(data.yacht.per_hour_price),


    user_id: 1,
    yacht: data.yacht.id,
    name: data.yacht.name,
    title: data.yacht.title,
    location: data.yacht.location,
    min_price: String(data.yacht.min_price),
    max_price: String(data.yacht.max_price),
    guest: String(data.yacht.guest),
    cancel_time_in_hour: String(data.yacht.cancel_time_in_hour),
    duration_hour: String(data.yacht.duration_hour),
    duration_minutes: String(data.yacht.duration_minutes),
    number_of_cabin: String(data.yacht.number_of_cabin),
    capacity: String(data.yacht.capacity),
    sleep_capacity: String(data.yacht.sleep_capacity),
    per_day_price: String(data.yacht.per_day_price),
    per_hour_price: String(data.yacht.per_hour_price),
    power: data.yacht.power,
    engine_type: data.yacht.engine_type,
    crew_member: data.yacht.crew_member,
    description: data.yacht.description,
    from_date: data.yacht.from_date,
    to_date: data.yacht.to_date,
    // ny_price: data.yacht.ny_price,
    // ny_firework: data.yacht.ny_firework,
    ny_status: false,
    // ny_availability: data.yacht.ny_availability,
    // ny_inclusion: data.yacht.ny_inclusion,
    }
    return obj
  };

  export const f1yachtData = (data) => {

    let obj = {
            // ...data.yacht,

            // user_id:1,
            // yacht:data.yacht.id,
            // min_price: String(data.yacht.min_price),
            // max_price: String(data.yacht.max_price),
            // guest: String(data.yacht.guest),
            // cancel_time_in_hour: String(data.yacht.cancel_time_in_hour),
            // duration_hour: String(data.yacht.duration_hour),
            // duration_minutes: String(data.yacht.duration_minutes),
            // number_of_cabin: String(data.yacht.number_of_cabin),
            // capacity: String(data.yacht.capacity),
            // sleep_capacity: String(data.yacht.sleep_capacity),
            // per_day_price: String(data.yacht.per_day_price),
            // per_hour_price: String(data.yacht.per_hour_price),


    user_id: 1,
    yacht: data.yacht.id,
    name: data.yacht.name,
    title: data.yacht.title,
    location: data.yacht.location,
    min_price: String(data.yacht.min_price),
    max_price: String(data.yacht.max_price),
    guest: String(data.yacht.guest),
    cancel_time_in_hour: String(data.yacht.cancel_time_in_hour),
    duration_hour: String(data.yacht.duration_hour),
    duration_minutes: String(data.yacht.duration_minutes),
    number_of_cabin: String(data.yacht.number_of_cabin),
    capacity: String(data.yacht.capacity),
    sleep_capacity: String(data.yacht.sleep_capacity),
    per_day_price: String(data.yacht.per_day_price),
    per_hour_price: String(data.yacht.per_hour_price),
    power: data.yacht.power,
    engine_type: data.yacht.engine_type,
    crew_member: data.yacht.crew_member,
    description: data.yacht.description,
    from_date: data.yacht.from_date,
    to_date: data.yacht.to_date,
    // ny_price: data.yacht.ny_price,
    // ny_firework: data.yacht.ny_firework,
    ny_status: false,
    // ny_availability: data.yacht.ny_availability,
    // ny_inclusion: data.yacht.ny_inclusion,
    }
    return obj
  };