import { z } from 'zod';

export const zodSchemaRegularYachts = z.object({
      // longitude: z.string().optional(),
    // latitude: z.string().optional(),
    // notes: z.string().optional(),
    // food_name: z.string().optional(),
    // food_price: z.string().transform(val => val ? Number(val) : undefined).optional(),
    // menucategory: z.string().optional(),
        // flag: z.string().optional(),
    // crew_language: z.string().optional(),
        // features: z.array(z.string()).optional(),
    // brand_id: z.string().optional(),
    // ny_availability: z.object({
    //   from: z.string(),
    //   to: z.string(),
    // }).optional(),


    yacht: z.any().optional(),
    user_id:z.any().optional(),
    name: z.string().min(1, "Name is required"),
    title: z.string().min(1, "Title is required"),
    location: z.string().min(1, "Location is required"),
    min_price: z.string().transform(val => Number(val)).pipe(z.number().positive()),
    max_price: z.string().transform(val => Number(val)).pipe(z.number().positive()),
    guest: z.string().transform(val => Number(val)).pipe(z.number().positive()),
    cancel_time_in_hour: z.string().transform(val => Number(val)).pipe(z.number().positive()),
    status: z.boolean().optional(),
    duration_hour: z.string().transform(val => Number(val)).pipe(z.number().positive()),
    duration_minutes: z.string().transform(val => Number(val)).pipe(z.number().positive()),
    number_of_cabin: z.string().transform(val => Number(val)).pipe(z.number().positive()),
    capacity: z.string().transform(val => Number(val)).pipe(z.number().positive()),
    sleep_capacity: z.string().transform(val => Number(val)).pipe(z.number().positive()),
    per_day_price: z.string().transform(val => Number(val)).pipe(z.number().positive()),
    per_hour_price: z.string().transform(val => Number(val)).pipe(z.number().positive()),
    length: z.any().optional(),
    power: z.string().optional(),
    engine_type: z.string().optional(),
    crew_member: z.string().optional(),
    description: z.string().optional(),
    category: z.string().optional(),
    inclusion: z.array(z.string()).optional(),
    category_name: z.string().optional(),
    yacht_name: z.string().optional(),
    ny_price: z.any().optional(),
    ny_firework: z.boolean().optional(),
    ny_status: z.boolean().optional(),
     ny_availability_from:z.any().optional() ,
     ny_availability_to:z.any().optional() ,

});


export const zodSchemaf1Yachts = z.object({
  // longitude: z.string().optional(),
// latitude: z.string().optional(),
// notes: z.string().optional(),
// food_name: z.string().optional(),
// food_price: z.string().transform(val => val ? Number(val) : undefined).optional(),
// menucategory: z.string().optional(),
    // flag: z.string().optional(),
// crew_language: z.string().optional(),
    // features: z.array(z.string()).optional(),
// brand_id: z.string().optional(),
// ny_availability: z.object({
//   from: z.string(),
//   to: z.string(),
// }).optional(),


yacht: z.any().optional(),
user_id:z.any().optional(),
name: z.string().min(1, "Name is required"),
title: z.string().min(1, "Title is required"),
location: z.string().min(1, "Location is required"),
min_price: z.string().transform(val => Number(val)).pipe(z.number().positive()),
max_price: z.string().transform(val => Number(val)).pipe(z.number().positive()),
guest: z.string().transform(val => Number(val)).pipe(z.number().positive()),
cancel_time_in_hour: z.string().transform(val => Number(val)).pipe(z.number().positive()),
status: z.boolean().optional(),
duration_hour: z.string().transform(val => Number(val)).pipe(z.number().positive()),
duration_minutes: z.string().transform(val => Number(val)).pipe(z.number().positive()),
number_of_cabin: z.string().transform(val => Number(val)).pipe(z.number().positive()),
capacity: z.string().transform(val => Number(val)).pipe(z.number().positive()),
sleep_capacity: z.string().transform(val => Number(val)).pipe(z.number().positive()),
per_day_price: z.string().transform(val => Number(val)).pipe(z.number().positive()),
per_hour_price: z.string().transform(val => Number(val)).pipe(z.number().positive()),
length: z.any().optional(),
power: z.string().optional(),
engine_type: z.string().optional(),
crew_member: z.string().optional(),
description: z.string().optional(),
category: z.string().optional(),
inclusion: z.array(z.string()).optional(),
category_name: z.string().optional(),
yacht_name: z.string().optional(),
// ny_price: z.any().optional(),
// ny_firework: z.boolean().optional(),
// ny_status: z.boolean().optional(),
//  ny_availability:z.any().optional() ,
// ny_inclusion: z.array(z.string()).optional(),
});




export const zodSchemaEmpty = z.object({});